services:
  mailpit:
    image: ghcr.io/axllent/mailpit:v1.30.7
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    environment:
      - MP_DISABLE_VERSION_CHECK=1
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - MP_SMTP_DISABLE_RDNS=1

  mailpit_starttls:
    image: ghcr.io/axllent/mailpit:v1.30.7
    ports:
      - "127.0.0.1:1026:1025"
      - "127.0.0.1:8026:8025"
    environment:
      - MP_DISABLE_VERSION_CHECK=1
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_DISABLE_RDNS=1
      - MP_SMTP_REQUIRE_STARTTLS=1
      - MP_SMTP_TLS_CERT=sans:localhost
      - MP_SMTP_TLS_KEY=sans:localhost

  mailpit_starttls_no_auth:
    image: ghcr.io/axllent/mailpit:v1.30.7
    ports:
      - "127.0.0.1:1027:1025"
      - "127.0.0.1:8027:8025"
    environment:
      - MP_DISABLE_VERSION_CHECK=1
      - MP_SMTP_DISABLE_RDNS=1
      - MP_SMTP_REQUIRE_STARTTLS=1
      - MP_SMTP_TLS_CERT=sans:localhost
      - MP_SMTP_TLS_KEY=sans:localhost
